import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Detail from "@/components/Detail";
import { Providers } from "./Providers";

const galmuri9 = localFont({
  src: [
    { path: "./fonts/Galmuri9.woff2", weight: "400" },
    { path: "./fonts/Galmuri9.ttf", weight: "400" },
  ],
  variable: "--font-galmuri",
  display: "swap",
});

export const metadata = {
  title: "My Pokedex",
  description: "My Pokedex Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className={galmuri9.className}>
      <body className="h-screen">
        <Providers>
          <Header />
          <div className="pt-[120px] pb-[80px] w-full h-full grid grid-cols-3">
            {/* pages 콘텐츠 */}
            <div className="scrollbar-custom w-full h-full col-span-2 overflow-y-auto z-10">
              {children}
            </div>
            {/* Detail 컴포넌트 */}
            <div className="w-full h-full col-span-1 relative">
              <Detail />
            </div>
          </div>
        </Providers>
        {/* 헤더 */}
      </body>
    </html>
  );
}
